apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: k61gmxrv6-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-076c5125a4.0my1.p3.openshiftapps.com/rhtap/rhtap-qe:f7d29f7b2bb1422607439f84a36e2d7ab22578ee@sha256:bae493b90e8905fdab65aa892f91a3b96891035b70e26ca4c870224fb3b3cb63
          name: container-image
